"use client";

import { useRef, useState } from "react";
import { ArchiveRestore, Database, Download, Keyboard, Layers3, Palette, Plus, Settings, SlidersHorizontal, Trash2, Upload, Zap } from "lucide-react";
import { toast } from "sonner";
import BoardBackgroundRenderer from "@/components/react-bits/BoardBackgroundRenderer";
import { HoldButton } from "@/components/react-bits/HoldButton";
import { JellyRadio } from "@/components/react-bits/JellyRadio";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Field, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Switch } from "@/components/ui";
import { PageContainer, PageHeader } from "@/components/layout/page";
import type { BoardView, Energy, MotionPreference, StartupPage, ThemePreference } from "@/domain/types";
import { downloadExport, parseImport } from "@/persistence/import-export";
import { useFlowvoraStore } from "@/store/flowvora-store";

const sections = [
  { id: "general", label: "General", icon: Settings }, { id: "appearance", label: "Appearance", icon: Palette },
  { id: "boards", label: "Board defaults", icon: Layers3 }, { id: "focus", label: "Focus", icon: Zap },
  { id: "tasks", label: "Task behavior", icon: SlidersHorizontal }, { id: "labels", label: "Labels", icon: ArchiveRestore },
  { id: "data", label: "Data", icon: Database }, { id: "shortcuts", label: "Shortcuts", icon: Keyboard },
] as const;

export function SettingsPage() {
  const data = useFlowvoraStore((state) => state.data);
  const updateSettings = useFlowvoraStore((state) => state.updateSettings);
  const replaceData = useFlowvoraStore((state) => state.replaceData);
  const resetApplication = useFlowvoraStore((state) => state.resetApplication);
  const clearDemo = useFlowvoraStore((state) => state.clearDemo);
  const createLabel = useFlowvoraStore((state) => state.createLabel);
  const updateLabel = useFlowvoraStore((state) => state.updateLabel);
  const deleteLabel = useFlowvoraStore((state) => state.deleteLabel);
  const fileRef = useRef<HTMLInputElement>(null);
  const [newLabel, setNewLabel] = useState("");
  const [newLabelColor, setNewLabelColor] = useState("#6F83C8");
  const workspaces = Object.values(data.workspacesById).sort((a, b) => a.position - b.position);
  const labels = Object.values(data.labelsById).sort((a, b) => a.name.localeCompare(b.name));
  const currentWorkspace = data.currentWorkspaceId ?? workspaces[0]?.id ?? "";

  const importFile = async (file: File | undefined) => {
    if (!file) return;
    const result = parseImport(await file.text());
    if (!result.success) { toast.error("Invalid backup", { description: result.message }); return; }
    const counts = `${Object.keys(result.data.workspacesById).length} workspaces, ${Object.keys(result.data.boardsById).length} boards, and ${Object.keys(result.data.tasksById).length} tasks`;
    if (!window.confirm(`Replace current Flowvora data with this backup (${counts})?`)) return;
    replaceData(result.data); toast.success("Import successful", { description: counts });
  };
  const updateAging = (key: "freshBeforeDays" | "staleAfterDays" | "stuckAfterDays", value: number) => updateSettings({ aging: { ...data.settings.aging, [key]: Math.max(1, value || 1) } });

  return <PageContainer><PageHeader title="Settings" description="Tune Flowvora’s behavior without adding noise to the working views." /><div className="grid gap-6 lg:grid-cols-[210px_minmax(0,1fr)]"><nav className="hidden lg:block"><div className="sticky top-24 grid gap-1">{sections.map(({ id, label, icon: Icon }) => <a key={id} href={`#${id}`} className="flex h-9 items-center gap-2.5 rounded-md px-3 text-sm text-secondary hover:bg-surface-hover hover:text-foreground"><Icon className="size-4" />{label}</a>)}</div></nav><div className="grid gap-5">
    <SettingsCard id="general" title="General" description="Choose where Flowvora opens and which workspace is the default."><div className="grid gap-4 sm:grid-cols-2"><Field label="Startup page"><Select value={data.settings.startupPage} onValueChange={(startupPage) => updateSettings({ startupPage: startupPage as StartupPage })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["/dashboard", "/workspaces", "/daily-flow", "/focus", "/activity", "/analytics"].map((value) => <SelectItem key={value} value={value}>{value.slice(1).replace("-", " ").replace(/^./, (character) => character.toUpperCase())}</SelectItem>)}</SelectContent></Select></Field><Field label="Default workspace"><Select value={data.settings.defaultWorkspaceId ?? "none"} onValueChange={(value) => updateSettings({ defaultWorkspaceId: value === "none" ? null : value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">None</SelectItem>{workspaces.map((workspace) => <SelectItem key={workspace.id} value={workspace.id}>{workspace.name}</SelectItem>)}</SelectContent></Select></Field></div></SettingsCard>
    <SettingsCard id="appearance" title="Appearance" description="Both themes are designed independently. Motion always has a static fallback."><div className="grid gap-5 md:grid-cols-[1fr_240px]"><div className="grid gap-5"><Field label="Theme"><JellyRadio options={[{ value: "light", label: "Light" }, { value: "dark", label: "Dark" }, { value: "system", label: "System" }]} value={data.settings.theme} onValueChange={(theme: ThemePreference) => updateSettings({ theme })} ariaLabel="Theme" /></Field><SettingToggle label="Compact mode" description="Reduce vertical spacing in dense productivity views." checked={data.settings.compactMode} onCheckedChange={(compactMode) => updateSettings({ compactMode })} /><SettingToggle label="Motion backgrounds" description="Allow one optional ambient effect on a board or Focus Mode." checked={data.settings.motionBackgrounds} onCheckedChange={(motionBackgrounds) => updateSettings({ motionBackgrounds })} /><Field label="Motion preference"><Select value={data.settings.motionPreference} onValueChange={(motionPreference) => updateSettings({ motionPreference: motionPreference as MotionPreference })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="system">Follow system</SelectItem><SelectItem value="reduce">Reduce motion</SelectItem><SelectItem value="allow">Allow motion</SelectItem></SelectContent></Select></Field></div><div className="relative min-h-52 overflow-hidden rounded-xl border border-border bg-[#0b0d10]"><BoardBackgroundRenderer background={{ type: "prism", intensity: 0.55, speed: 0.4 }} motionEnabled={data.settings.motionBackgrounds} reducedMotion={data.settings.motionPreference === "reduce"} /><div className="absolute inset-x-4 bottom-4 z-10 rounded-lg border border-white/10 bg-black/40 p-3 text-white backdrop-blur"><p className="text-xs font-semibold">Prism preview</p><p className="mt-1 text-[10px] text-white/60">Optional, isolated, and never mounted inside task cards.</p></div></div></div></SettingsCard>
    <SettingsCard id="boards" title="Board defaults" description="New boards use these choices; existing boards keep their own settings."><div className="grid gap-4 sm:grid-cols-2"><Field label="Default view"><JellyRadio options={[{ value: "kanban", label: "Kanban" }, { value: "canvas", label: "Canvas" }]} value={data.settings.defaultBoardView} onValueChange={(defaultBoardView: BoardView) => updateSettings({ defaultBoardView })} ariaLabel="Default board view" /></Field><SettingToggle label="Flow Mode" description="Show subtle stage progression on new boards." checked={data.settings.defaultFlowMode} onCheckedChange={(defaultFlowMode) => updateSettings({ defaultFlowMode })} /></div><div className="mt-5"><p className="mb-2 text-sm font-medium">Default stages</p><div className="flex flex-wrap gap-2">{data.settings.newBoardColumns.map((column, index) => <span key={`${column.name}-${index}`} className="rounded-full border border-border bg-surface-raised px-2.5 py-1 text-xs"><span className="mr-1.5 inline-block size-2 rounded-full" style={{ backgroundColor: column.accent }} />{column.name}</span>)}</div></div></SettingsCard>
    <SettingsCard id="focus" title="Focus" description="Timer sessions never auto-start."><div className="grid gap-4 sm:grid-cols-2"><Field label="Default timer (minutes)"><Input type="number" min={1} max={240} value={data.settings.focusDurationMinutes} onChange={(event) => updateSettings({ focusDurationMinutes: Math.max(1, Number(event.target.value) || 25) })} /></Field><Field label="Available energy"><JellyRadio options={[{ value: "low", label: "Low" }, { value: "medium", label: "Medium" }, { value: "deep", label: "Deep" }]} value={data.settings.availableEnergy} onValueChange={(availableEnergy: Energy) => updateSettings({ availableEnergy })} size="sm" ariaLabel="Default available energy" /></Field></div></SettingsCard>
    <SettingsCard id="tasks" title="Task behavior" description="Aging is based on last update; Stuck is based on time in an active or review stage."><div className="grid gap-4 sm:grid-cols-3"><Field label="Fresh under (days)"><Input type="number" min={1} value={data.settings.aging.freshBeforeDays} onChange={(event) => updateAging("freshBeforeDays", Number(event.target.value))} /></Field><Field label="Stale after (days)"><Input type="number" min={data.settings.aging.freshBeforeDays} value={data.settings.aging.staleAfterDays} onChange={(event) => updateAging("staleAfterDays", Number(event.target.value))} /></Field><Field label="Stuck after (days)"><Input type="number" min={1} value={data.settings.aging.stuckAfterDays} onChange={(event) => updateAging("stuckAfterDays", Number(event.target.value))} /></Field></div></SettingsCard>
    <SettingsCard id="labels" title="Labels" description="Reusable labels remain scoped to their workspace."><form onSubmit={(event) => { event.preventDefault(); if (!newLabel.trim() || !currentWorkspace) return; createLabel(currentWorkspace, newLabel, newLabelColor); setNewLabel(""); }} className="mb-4 flex flex-col gap-2 sm:flex-row"><Input value={newLabel} onChange={(event) => setNewLabel(event.target.value)} placeholder="New label name" /><Input type="color" value={newLabelColor} onChange={(event) => setNewLabelColor(event.target.value)} className="w-16 p-1" aria-label="Label color" /><Button type="submit" variant="secondary" disabled={!newLabel.trim() || !currentWorkspace}><Plus />Add label</Button></form><div className="grid gap-2">{labels.map((label) => <div key={label.id} className="flex items-center gap-3 rounded-lg border border-border bg-surface-raised px-3 py-2"><Input type="color" value={label.color} onChange={(event) => updateLabel(label.id, { color: event.target.value })} className="h-8 w-10 border-0 bg-transparent p-0" aria-label={`${label.name} color`} /><input defaultValue={label.name} onBlur={(event) => updateLabel(label.id, { name: event.target.value })} className="min-w-0 flex-1 bg-transparent text-sm outline-none" aria-label="Label name" /><span className="hidden text-xs text-muted sm:block">{data.workspacesById[label.workspaceId]?.name}</span><Button variant="ghost" size="icon-sm" onClick={() => { if (window.confirm(`Delete label “${label.name}”?`)) deleteLabel(label.id); }} aria-label={`Delete ${label.name}`}><Trash2 /></Button></div>)}</div></SettingsCard>
    <SettingsCard id="data" title="Data" description="Everything is local to this browser. Export backups whenever you want a portable copy."><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border bg-surface-raised p-3"><strong className="text-lg">{Object.keys(data.workspacesById).length}</strong><span className="mt-1 block text-xs text-muted">Workspaces</span></div><div className="rounded-lg border border-border bg-surface-raised p-3"><strong className="text-lg">{Object.keys(data.boardsById).length}</strong><span className="mt-1 block text-xs text-muted">Boards</span></div><div className="rounded-lg border border-border bg-surface-raised p-3"><strong className="text-lg">{Object.keys(data.tasksById).length}</strong><span className="mt-1 block text-xs text-muted">Tasks</span></div></div><div className="mt-5 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => { downloadExport(data); toast.success("Backup exported"); }}><Download />Export JSON</Button><Button variant="secondary" onClick={() => fileRef.current?.click()}><Upload />Import JSON</Button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={(event) => void importFile(event.target.files?.[0])} /><Button variant="ghost" onClick={() => { if (window.confirm("Clear all current content and keep default settings?")) clearDemo(); }}>Clear demo/content</Button></div><div className="mt-6 rounded-xl border border-danger/20 bg-danger-soft p-4"><h3 className="text-sm font-semibold text-danger">Reset Flowvora</h3><p className="mt-1 text-xs leading-5 text-secondary">Deletes only Flowvora’s own local storage key, then restores the demonstration workspace.</p><div className="mt-4"><HoldButton onComplete={() => { resetApplication(); toast.success("Flowvora reset"); }}>Hold to reset Flowvora</HoldButton></div></div></SettingsCard>
    <SettingsCard id="shortcuts" title="Keyboard shortcuts" description="Single-key shortcuts pause while you type in an input."><div className="divide-y divide-border rounded-lg border border-border">{[["Ctrl / Cmd + K", "Command palette"], ["N", "Quick create"], ["D", "Dashboard"], ["B", "Workspaces"], ["F", "Focus Mode"], ["Escape", "Close drawer or dialog"]].map(([keys, action]) => <div key={keys} className="flex items-center justify-between px-4 py-3 text-sm"><span className="text-secondary">{action}</span><kbd className="rounded border border-border bg-surface-raised px-2 py-1 font-mono text-xs">{keys}</kbd></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Activity history limit"><Input type="number" min={50} max={5000} value={data.settings.activityLimit} onChange={(event) => updateSettings({ activityLimit: Math.max(50, Number(event.target.value) || 750) })} /></Field><div className="rounded-lg border border-border bg-surface-raised p-3 text-xs text-secondary"><p><strong className="text-foreground">Schema:</strong> v{data.schemaVersion}</p><p className="mt-1"><strong className="text-foreground">Persistence:</strong> flowvora:state</p><p className="mt-1"><strong className="text-foreground">Activity:</strong> {data.activities.length} events</p></div></div></SettingsCard>
  </div></div></PageContainer>;
}

function SettingsCard({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <Card id={id} className="scroll-mt-24"><CardHeader><div><CardTitle className="text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></div></CardHeader><CardContent>{children}</CardContent></Card>; }
function SettingToggle({ label, description, checked, onCheckedChange }: { label: string; description: string; checked: boolean; onCheckedChange: (checked: boolean) => void }) { return <label className="flex items-center justify-between gap-4 rounded-lg border border-border bg-surface-raised p-3"><span><span className="block text-sm font-medium">{label}</span><span className="mt-0.5 block text-xs leading-5 text-muted">{description}</span></span><Switch checked={checked} onCheckedChange={onCheckedChange} /></label>; }
